version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Dharani@2004
      MYSQL_DATABASE: urlshortenerdb
      MYSQL_USER: root
      MYSQL_PASSWORD: Dharani@2004
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  springboot:
    image: your-springboot-image
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/urlshortenerdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Dharani@2004
    depends_on:
      - mysql
    ports:
      - "8067:8067"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
